name: "⚙️ CI Feature Branch"

on:
  push:
    branches:
      - feature**
      - '[0-9].[0-9].x'
      - 'v[0-9].[0-9].[0-9]'
      - 'v[0-9].[0-9].x'
      - docs**

permissions:
  contents: read

concurrency:
  group: ci-feature-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-terraform:
    name: 🧪 terraform
    uses: ./.github/workflows/tf-validate.yml
    with:
      modules: '["dynamodb-table","iam-role","lambda-layer","sqs-queue","sns-topic","lambda-function","glue-job"]'

  validate-catalog:
    name: 🧩 catalog
    uses: ./.github/workflows/catalog-validate.yml

  open-pr-to-main:
    name: 🔓 open-pr-to-main
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - validate-terraform
      - validate-catalog
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v6

      - name: 🔓 PR to main
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          base: main
          branch: ${{ github.ref }}
          title: "pr(main): ${{ github.ref }} -> main"
          body-path: ".github/pull_request_template.md"
          labels: "github-bot 🤖"
          commit-message: "bot: automatic PR opening to main branch"
